### ISSUE TITLE
php versiyon hatası

### ISSUE THREAD

**Issue by abdullahbilgin** [karmaphp/karma#1]
Problem 1
    - Installation request for doctrine/annotations ^1.5 -> satisfiable by doctrine/annotations[v1.5.0].
    - doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (7.0.18) does not satisfy that requirement.

**Comment by irfanevrens** [comment]
@abdullahbilgin tekrar dener misiniz?
